version: "3.7"

services:

  manga-frontend:
    container_name: manga-frontend
    build: ./
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
